# This is a basic workflow to help you get started with Actions

name: CI

env:
  VERCEL_ORG_ID: Iu7YgdCjNBg1lPtuGkmslAzP
  VERCEL_PROJECT_ID: prj_U53Engt2egaBycSBkTX2CTXULwrP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=BtOGtJcC7hA37MfwXSWqYpGv
      - name: Build Project Artifacts
        run: vercel build --prod --token=BtOGtJcC7hA37MfwXSWqYpGv
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=BtOGtJcC7hA37MfwXSWqYpGv
